
<form
<?php

foreach ($this->formFilter->getAttribs() as $key => $atribute)
{
    echo $key.'='.'"'.$atribute.'" ';
}
?>>
<p>
Учебный год <?php echo $this->formFilter->studyYearStart;?>-<span id="studyYearEnd"><?php echo $this->studyYearEnd;?></span>
</p>
<p>курс <?php echo $this->formFilter->kurs;?> &nbsp; форма обучения&nbsp;<?php echo $this->formFilter->osnov;?> 
</p>
<p>группа <?php echo $this->formFilter->group;?>
</p>


</form>
