<form action="<?php echo $this->baseUrl;  ?>/sprav/<?php echo $this->curcont; ?>/<?php echo $this->curact; ?>" method="post">

<textarea tabindex="1" class="typicadd" name="title"><?php
$title=isset($entry->title)?$this->escape($entry->title):"";
echo $title; 
?>
</textarea> 
<br>Шифр&nbsp;<input class="typic_input" name="numeric_title" id="numeric_title" >
<input type="hidden" name="id" value="<?php echo $this->id; ?>" />
<input type="submit" name="add" value="&nbsp;&nbsp;" class="apply_button" title="Применить"/>

</form>