<?php echo $this->render('header.phtml'); ?>
 

<div id="left">
<ul>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/discipline">Дисциплины вступительных испытаний</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/examtypes">Типы вступительных испытаний</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/division">Отделения обучения</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/payment">Способы оплаты</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/idendoc">Документы, удостоверяющие личность</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/doccopy">Типы документов (копия/оригинал)</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/social">Категории льгот</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/awards">награды абитуриентов</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/edudoc">Документ об образовании</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/formaobuch">Форма обучения</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/idenlive">Откуда родом абитуриент</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/rooms">Потребность в общежитии</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/langs">Иностранные языки</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/personoperations">Операции над субъеками</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/outcontrols">Формы выходного контроля</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/studyoperations">Типы занятий студентов</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/kafedry">Кафедры</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/disciplinestud">Дисциплины преподаваемые</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/bells">Расписание звонков</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/specs">Специальности</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/facultets">Факультеты</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/sprav/doctypes">Типы формируемых документов</a></li>
<!--<li><a href="<?php // echo $this->baseUrl; ?>/sprav/leaders">Руководство*</a></li>-->
<li><a href="<?php echo $this->baseUrl; ?>/sprav/position">Должности</a></li>
<!--<li><a href="<?php // echo $this->baseUrl; ?>/sprav/people">Сотрудники*</a></li>-->
<li><a href="<?php echo $this->baseUrl; ?>/sprav/about">Общая информация</a></li>
</ul>
</div>