
<p class="close_popup2" onclick='$("#studentsFree").togglePopup(); ' title="Отмена"></p>
<h4>Назначение абитуриентов</h4>

<div id="studentsFreeList">

<?php
if (count ($this->studsFree)>0)
{
	?>
	<div class="toolbar">
	<img alt="Выбрать всех" src="<?php echo $this->baseUrl; ?>/public/images/selectAll.png" 
		class="imglink" title="Выбрать всех" 
		onclick="markAllClass('userid');"
		/>
	<img alt="Отметить через одного" src="<?php echo $this->baseUrl; ?>/public/images/selectAll_from_one.png" 
		class="imglink" title="Отметить через одного" 
		onclick="markAllClassFromOne('userid');"
		/>
	<img alt="Снять все отметки" src="<?php echo $this->baseUrl; ?>/public/images/unselectAll.png" 
		class="imglink" title="Снять все отметки" 
		onclick="unmarkAllClass('userid');"
		/>
	</div>
<p>Назначить выбранных абитуриентов 
в группу <strong><?php echo $this->subgroupInfo["groupTitle"]?></strong>
подгруппу <strong><?php echo $this->subgroupInfo["subgroupTitle"]?></strong>
</p>

	<form id="freeStudsForm" name="freeStudsForm" action="<?php echo $this->baseLink; ?>/assign2subgroup" method="post">
	<p>Формирование номеров зачетных книжек. 
		Год<?php echo $this->formAbiturs->zach_year; ?>. 
		Начать нумерацию с <?php echo $this->formAbiturs->zach_num; ?>
		<?php echo $this->formAbiturs->ok; ?>
	</p>
	<input type="hidden" name="subgroupTo" id="subgroupTo" value="<?php echo $this->subgroupInfo["id"]; ?>">
	<div class="th">
			<div class="Col_0">
				</div>
			<div class="Col_1">№</div>
			<div class="Col_2">Ф.И.О.</div>
			<div class="Col_3">ин.яз.</div>
			<div class="Col_4">коммерч.</div>
			<div class="Col_5">проживает</div>
			<div class="Col_6">поступил</div>
			<div class="Col_7">приказ</div>
	</div>
	<?php 
	$n=1;
	foreach ($this->studsFree as $student) 
	{
		$tr=$tr==1?2:1;
		?>
		<div class="tr<?php echo $tr; ?>">
			<div class="Col_0">
				<input type="checkbox" name="userid[]" class="userid" value="<?php echo $student["userid"] ;	?>">
				</div>
			<div class="Col_1"><?php echo $n;?></div>
			<div class="Col_2"><?php echo $student["fio"] ;	?></div>
			<div class="Col_3"><?php echo $this->utf8substr($student["langTitle"],0,3) ;	?></div>
			<div class="Col_4"><small><?php echo $student["payTitle"] ;	?></small></div>
			<div class="Col_5"><?php echo $student["idenTitle"] ;	?></div>
			<div class="Col_6"><?php echo $student["abitur_year"] ;	?></div>
			<div class="Col_7"><?php echo $student["prikaz"] ;	?></div>
		</div>
		<?php
		$n++; 
	}
	?>
	</form>
	<?php 
}
else echo "Список пуст"; 
// есть ли такие и построить форму еслли есть 
// или не обнаружено
?>
</div>
