<?php echo $this->render('header.phtml'); ?>

<div id="left">
<ul>
<!--<li><a href="<?php //echo $this->baseUrl; ?>/<?php //echo $this->currentModuleName; ?>/importpriem">Импорт из приемной комиссии</a></li>-->
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/groups">Группы</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/personal">Манипуляции с контингентом</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/studyplan">Учебные планы<br>(контрольные параметры)</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/attendance">Посещаемость,<br>аттестационные листы</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/outcontrol">Выходной контроль(ведомости)</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/orders">Отчеты*</a></li>
</ul>
</div>