<div id="trTemplate" class="hidden">
	<div class="tr1" >
		<div class="Col_1">
			<span class="leftArrowIcoMedium" title="Убрать"
			onclick="moveNode('usersGranted',false,$(this));">
			<input type="hidden" name="userid[]" value="0">
			</span>
		</div>
		<div class="Col_2"></div>
		<div class="Col_3"></div>
		<div class="Col_4"><?php echo $this->privSelList->setValue("100");?></div>
	</div>
</div>