<div class="th">
	<div class="Col_1">Логин</div>
	<div class="Col_2">ФИО</div>
	<div class="Col_3">Действие</div>
</div>

<?php
if (count($this->usersInRole >0))
{
?>
<?php
$tr=1;
foreach ($this->usersInRole as $user) 
{
	$tr=$tr==1?2:1;
	?>
	<div class="tr<?php echo $tr;?>" id="user_<?php echo $user["id"]; ?>">
		<div class="Col_1"><?php echo $user["login"];?></div>
		<div class="Col_2"><?php echo $user["fio"];?></div>
		<div class="Col_3">
			<span class="rightArrowIcoMedium" title="Добавить"
			onclick="moveNode('usersList','usersGranted',$(this));"
			>			
			<input type="hidden" name="userid[]" value="<?php echo $user["id"]; ?>">
			</span>
		</div>
	</div>
	<?php 
	;
} 
}
?>