<div id="delFormWrapper" style="display:none;">
<p class="close_popup2"
	onclick='$("#delFormWrapper").togglePopup(); ' title="отмена"></p>
<h4>Исключить преподавателя из списка указанной дисциплины</h4>
<p>Введите слово<br>
<span class="error"><?php echo $this->confirmWord; ?></span>
<br>для подтверждения</p>
<form
<?php
foreach ($this->formDel->getAttribs() as $key => $atribute)
{
	echo $key.'='.'"'.$atribute.'" ';
}
?>>
<?php echo $this->formDel->discipline; ?>
<?php echo $this->formDel->teacher; ?>
<?php echo $this->formDel->confirmWord; ?>
<?php echo $this->formDel->OK; ?>
</form>
</div>
