<form 
<?php

foreach ($this->formEdit->getAttribs() as $key => $atribute)
{
    echo $key.'='.'"'.$atribute.'"';
}
?>>
<p class="close_popup2" onclick='$("#formEdit").togglePopup(); ' title="отмена"></p>
<?php echo $this->formEdit->id; ?>
<?php echo $this->formEdit->kurs; ?>
<div class="table">
<div class="th">
	<div class="Col_1">Дисциплина</div>
	<div class="Col_2">зачетов</div>
	<div class="Col_3">экзаменов</div>
	<div class="Col_4">контр.работ</div>
	<div class="Col_5">курсовых работ</div>
	<div class="Col_6">курсовых проектов</div>
	
</div>

<div class="tr1">
	<div class="Col_1"><?php echo $this->formEdit->discipTitle; ?></div>
	<div class="Col_2"><?php echo $this->formEdit->zachCount; ?></div>
	<div class="Col_3"><?php echo $this->formEdit->examCount; ?></div>
	<div class="Col_4"><?php echo $this->formEdit->kontrCount; ?></div>
	<div class="Col_5"><?php echo $this->formEdit->kursWCount; ?></div>
	<div class="Col_6"><?php echo $this->formEdit->kursPCount; ?></div>
	
</div>
</div>
<?php echo $this->formEdit->OK; ?>
</form>
