<div id="discipline" class="tr" style="display:none;">
	<div class="Col_1">
	<?php 
		 
		echo $this->formD->discipline;  
	?>
	</div>
	
	<div class="Col_2"><?php echo $this->formD->zachetCount; ?></div>
	<div class="Col_3"><?php echo $this->formD->examCount; ?></div>
	<div class="Col_4"><?php echo $this->formD->kontrCount; ?></div>
	<div class="Col_5"><?php echo $this->formD->kursWCount; ?></div>
	<div class="Col_6"><?php echo $this->formD->kursPCount; ?></div>
	<div class="Col_7">
		<img alt="Удалить" src="<?php echo $this->iconpath; ?>human_o2_16x16/actions/gtk-remove.png" class="imglink" 
		title="Удалить дисциплину"
		onclick='' 
		/>
		</div>
	

</div>